version: "3.8"
services:
    web:
        build:
            args:
                environment: production
        environment: 
            RAILS_ENV: production
            RAILS_SERVE_STATIC_FILES: 'true'