default: &default
  adapter: postgresql 
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.postgres[:username] { raise "Make sure you have configured a postgres user" } %>
  password: <%= Rails.application.credentials.postgres[:password] { raise "Make sure you have configured a postgres pass"} %>

development:
  <<: *default
  database: CrewLinkStatus_development 

test:
  username: travis
  database: CrewLinkStatus_test

production:
  <<: *default
  database: CrewLinkStatus_production